[tools]
java = "lts"
google-java-format = "latest"
clojure = "latest"
maven = "latest"
gradle = "latest"
go = "latest"
perl = "latest"
python = "latest"
uv = "latest"
node = "lts"
npm = "latest"
rust = "latest"
zig = "latest"
zls = "latest"
bat = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
pandoc = "latest"
prettier = "latest"
ripgrep = "latest"
shellcheck = "latest"
trivy = "latest"
yq = "latest"
